# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Spazieren' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spazieren
pod "AFNetworking"
pod "YYModel"
pod "SDWebImage"
pod "pop"
pod "FMDB"
pod "SVProgressHUD"





end
